import "./globals.css";

import { Inter, Playfair_Display } from "next/font/google";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import ThemeProvider from "./_lib/ThemeProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata = {
  title: "Cultre BOAT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${playfair.variable} antialiased min-h-screen bg-texture texture-normal transition-all duration-300 ease-out`}
      >
      <ThemeProvider>
        <Header />
        <main>{children}</main>
        <Footer />
      </ThemeProvider>
      </body>
    </html>
  );
}
